apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-myfork
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-myfork
    app.kubernetes.io/part-of: devfile-sample-python-basic-myfork
  name: devfile-sample-python-basic-myfork
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-myfork
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-myfork
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/bkorren-tenant/devfile-sample-python-basic-myfork/devfile-sample-python-basic-myfork@sha256:b0f76b0b6cc5f2ae761e0543f6857f011e0e6a9f513f6b8b9a7bc2298260d385
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
